::: {.content-visible when-format="html"}
{{< include _macros.tex >}}
:::

# Distance Measures {#sec-eval-det}

As discussed in @sec-survtsk, evaluating the distance between point predictions of survival time and ground truth event times is fundamentally problematic when censoring is present.\index{survival time}
In particular, there is no principled way to define a metric that accurately reflects the average discrepancy between predicted survival times and all event times.

The most commonly discussed distance measure in the literature is the mean absolute error (MAE):\index{mean absolute error}

$$
\operatorname{MAE}(\tt, \mathbf{\hatt}) = \mean{\vert t_i - \hatt_i \vert},
$$ {#eq-mae}

where $\dvec{t}{n}$ and $\dvec{\hatt}{n}$ are observed follow-up times and predicted survival times, respectively.
In the literature, (@eq-mae) is occasionally adapted for survival analysis by restricting evaluation to uncensored observations only [@Wang2017].
However, restricting evaluation in this way introduces substantial bias.
@Qi2023 show that naively applying (@eq-mae) to uncensored data can induce model performance rankings inconsistent with those obtained from the oracle MAE. This remains true even when incorporating inverse probability of censoring weights\index{inverse probability of censoring weights}.

A pseudo-value-based approach\index{pseudo-values} (see @sec-pseudo-value-reduction for details about pseudo-values) has been shown, under controlled simulation settings, to induce the same model rankings as the oracle MAE [@Qi2023].
However, this approach is not intended to, nor does it, recover a meaningful measure of absolute distance between predicted survival times and the ground truth event times --- pseudo-values are estimates and do not represent the true outcome.

Given these limitations, distance-based evaluations should generally be avoided.
Instead, discrimination-based measures (@sec-eval-crank) may be used to evaluate survival time predictions, while being clear that this evaluates relative risks only and does not attempt to quantify the distance between predictions and truth.

## Conclusion

:::: {.callout-warning icon=false}

## Key takeaways

* Point predictions of survival time cannot be evaluated using standard distance-based error measures in a principled way when censoring is present.
* Existing approaches may support relative comparison of models but do not resolve the fundamental ambiguity created by unobserved event times.
* As a result, discrimination-based evaluation should be preferred, with careful interpretation of what is, and is not, being evaluated.

::::
