::: {.content-visible when-format="html"}
{{< include _macros.tex >}}
:::

# Choosing Measures {#sec-choosing-measures}

There are many survival measures\index{performance measure} to choose from, and selecting the right one for a given task may seem daunting.
Below are a few heuristics to support decision-making.
First and foremost, evaluation should always be according to the goals of analysis, which means using discrimination measures\index{discrimination} to evaluate relative risk predictions\index{relative risk}, calibration\index{calibration} measures to evaluate average agreement between predictions and observed outcomes, and scoring rules\index{scoring rules} to evaluate overall performance and distribution predictions.

For discrimination measures, consider Harrell's C and Uno's C.\index{concordance index!Harrell's C}\index{concordance index!Uno's C}
While other discrimination measures can assess time-dependent ranking performance, time-dependent predictive performance can also be examined through scoring rules.
If only one measure is to be reported, then Uno's C may be preferred.
Although Uno's C can have higher variance than Harrell's C [@Rahman2017; @Schmid2012], it is less likely to overestimate concordance as censoring increases [@Rahman2017].
Moreover, the variance can be transparently captured and reported through techniques such as bootstrapping.
In practice, the choice of measure matters less than ensuring your reporting is transparent and honest [@Sonabend2022; @Therneau2020].\index{C-hacking}

To assess the calibration of a single model, graphical comparisons to the Kaplan-Meier estimator\index{Kaplan-Meier estimator} provide a useful and interpretable way to assess model fit (@sec-calib-km). \index{calibration!plots}
When choosing between models, D-calibration\index{calibration!D-calibration} can be meaningfully optimized and thus used for model comparison.

When picking scoring rules, the survival Brier score (@eq-sbs) provides a useful score for developing prediction error curves (@sec-pecs).
For a quantity that summarizes overall predictive ability, the integrated SBS (@eq-igs) is most commonly used in the literature though its properness is susceptible to different censoring patterns.
The RCLL\index{right-censored log loss} (@sec-rules-log) is intuitive and is proven strictly proper when censoring is conditionally event-independent [@Rindt2022; @Yanagisawa2023], but may require numerical approximation of the density function (@sec-distributions-continuous).
Most importantly, the choice of evaluation measure(s) should be decided up-front and not selected based on preliminary results.
When reporting scoring rules, consider the ERV representation which provides a meaningful interpretation as "performance increase over baseline".\index{explained residual variation}

Given the limited research currently available, evaluation of survival time predictions should be treated with caution and new developments in the literature should be monitored.

For automated model optimization\index{hyperparameter optimization}, tuning with a scoring rule should capture discrimination and calibration simultaneously [@Kopper2026; @Rindt2022; @Yanagisawa2023].
However, if you are developing a model to maximize separation and calibration truly matters less, then prefer Harrell's C over Uno's C, as any bias in the measure should affect models similarly, making lower variance potentially preferable.
Finally, avoid using a measure of calibration alone for tuning, as that will push models towards acting like a non-parametric estimator.
