project:
  type: book
  output-dir: _book

crossref:
  chapters: true
  cnj-prefix: Box
  cnj-title: Box

toc: true
number-sections: true
bibliography: library.bib

book:
  title: "Machine Learning in Survival Analysis"
  reader-mode: true
  repo-url: https://github.com/RaphaelS1/MLSA/
  repo-actions: [edit, issue, source]
  repo-subdir: book
  appendices:
  - appendix.qmd
  author: "Raphael Sonabend, Andreas Bender"
  downloads: pdf
  page-footer:
    left: |
      Sonabend, R. and Bender, A. Machine Learning in Survival Analysis. 2022.
    right: |
      All content licenced under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - machinelearning.qmd
    - survival.qmd
    - models.qmd
    - classical.qmd
    - mlmodels.qmd
    - forests.qmd
    - svm.qmd
    - boosting.qmd
    - neuralnetworks.qmd
    - evaluation.qmd
    - pipelines.qmd
    - alternatives.qmd
    - software.qmd
    # - julia.qmd
    - conclusion.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    author-meta: "Raphael Sonabend and Andreas Bender"
    code-link: true
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
  pdf:
    documentclass: scrbook
    lof: true
    lot: true
    fig-cap-location: bottom
    tbl-cap-location: bottom
    geometry:
      - margin=1in
      - heightrounded
    biblio-style: apalike
    keep-tex: true
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: true
    hyperrefoptions:
      - linktoc=all
    include-in-header:
      text: |
        \usepackage{makeidx}
        \usepackage{mathtools}
        \usepackage{algpseudocode,algorithm,algorithmicx}
        \makeindex
    include-after-body:
      text: |
        \printindex

latex-auto-install: true

knitr:
  opts_chunk:
    cache: true
    cache.lazy: false
    R.options:
      knitr.graphics.auto_pdf: true
    attr.source: ".numberLines"
