project:
  type: book

crossref:
  chapters: true
  eq-prefix: ""

number-sections: true
bibliography: library.bib

book:
  title: "Machine Learning for Survival Analysis"
  repo-url: https://github.com/mlsa-book/MLSA/
  repo-subdir: book
  search: true
  cover-image: Figures/cover-new.svg
  sidebar:
    style: "floating"
    collapse-level: 1
    border: true
    search: true
  page-footer:
    left: "All content licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
    center: "&copy; Andreas Bender, Raphael Sonabend"
    right: Built with [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  chapters:
    - text: " "
      file: index.qmd
    - 00-notation.qmd
    - 01-introduction.qmd
    - part: Machine Learning and Survival Analysis
      chapters:
        - 02-machine-learning.qmd
        - 03-survival-analysis.qmd
        - 04-event-history-analysis.qmd
        - 05-survival-task.qmd
    - part: Evaluation
      chapters:
        - 06-discrimination.qmd
        - 07-calibration.qmd
        - 08-scoring-rules.qmd
        - 09-distance-measures.qmd
        - 10-choosing-measures.qmd
    - part: Models
      chapters:
        - 11-core-models.qmd
        - 12-random-forests.qmd
        - 13-support-vector-machines.qmd
        - 14-gradient-boosting-machines.qmd
        - 15-neural-networks.qmd
        - 16-choosing-models.qmd
    - part: Reduction Techniques
      chapters:
        - 17-reductions-overview.qmd
        - 18-ipcw-reductions.qmd
        - 19-pseudo-value-reductions.qmd
        - 20-partition-reductions.qmd
        - 21-event-history-reduction.qmd
    - references.qmd

format:
  html:
    css: styles.css
    theme: cosmo
    author-meta: "Andreas Bender and Raphael Sonabend"
    highlight-style: printing
    reference-location: margin
  pdf:
    pdf-engine: pdflatex
    documentclass: style/krantz
    classoption: krantz2
    lof: false
    lot: false
    toc: false
    toc-depth: 2
    fig-cap-location: bottom
    tbl-cap-location: top
    urlcolor: "blue"
    linkcolor: "black"
    biblio-style: apalike
    keep-tex: true
    include-in-header:
      text: |
        \input{_macros.tex}
        \makeindex
    include-after-body:
      text: |
        \printindex

latex-auto-install: true
