project:
  type: book

book:
  title: "Machine Learning Survival Analysis"
  author: "Raphael Sonabend"
  date: "11/23/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - learning.qmd
    - survival.qmd
    - classical.qmd
    - forests.qmd
    - svm.qmd
    - boosting.qmd
    - neuralnetworks.qmd
    - evaluation.qmd
    - alternatives.qmd
    - extensions.qmd
    - software.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
