project:
  type: book

book:
  title: "Machine Learning in Survival Analysis"
  reader-mode: true
  repo-url: https://github.com/RaphaelS1/MLSA/
  author: "Raphael Sonabend"
  downloads: pdf
  page-footer:
    left: |
      Sonabend, R. Machine Learning in Survival Analysis. 2022.
    right: |
      All content licenced under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - machinelearning.qmd
    - survival.qmd

    - part : models.qmd
      chapters:
        - classical.qmd
        - mlmodels.qmd
        - forests.qmd
        - svm.qmd
        - boosting.qmd
        - neuralnetworks.qmd

    - part: evaluation.qmd
      chapters:
        - evaluation.qmd

    - alternatives.qmd
    - software.qmd
    - julia.qmd
    - conclusion.qmd
    - references.qmd

bibliography: library.bib

format:
  html:
    theme: cosmo
    author-meta: "Raphael Sonabend"
  pdf:
    documentclass: scrreprt
    include-in-header: # for emojis in margins
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
