---
abstract: TODO (150-200 WORDS)
---

{{< include _setup.qmd >}}

# Event-history Analysis {#sec-eha}

{{< include _wip.qmd >}}

___


This section generalises the single-event setting by viewing time-to-event data as data in which one could observe multiple, potentially mutually exclusive events.
In this generalisation, data is sometimes refered to *event-history data* and its analysis as *event-history analysis* (EHA).
@tbl-eha classifies the different types of data that could occur in EHA, differentiated between the number of occurences of the events (rows) and whether the events are of same or different types (columns).

| | Same event type | Competing event types |
|-|-|-|
| One/first event | single event | competing risks |
| Multiple events | recurrent events | multi state |
: Classifying events in event-history analysis. Top row refers either to the setting where only one event occurs, or the setting where multiple events occur but only the time to the first event is of interest. {#tbl-eha}

One can think about event history in terms of transitions between different states, as illustrated in @fig-eha.
Usually, a subject starts out in state 0 (for example, 'healthy') and transitions to different states from there.
States from which further transitions are possible are called *transient*, otherwise a state is called *terminal*.
If no transition happens within the follow-up time, the subject remains in the initial state, in event history terms the observation is censored for this transition.

In the *single event* setting (@fig-eha, left panel), a subject can only transition to one state (the event of interest).
In the *competing risks* setting (@fig-eha, middle panel, see @sec-competing-risks), a subject could transition to any of the $K$ mutually exclusive states, thus the subject is *at risk* for a transition to multiple states.
However, once one of them occurs, it is impossible to transition to another (for example, death from different causes).
In both cases, the event needs not be terminal, we just end the observation after the first occurence of an event.

In the most general case, the *multi-state* setting (@fig-eha right panel, see @sec-multi-state), there are multiple transient and terminal states with potential back transitions (for example, moving between different stages of an illness with the possibility of (partial) recovery and death as terminal event).
The *recurrent events setting* is as a special case of the multi-state setting but could also be treated as a more general case of the single event setting with correlated observations (@sec-recurrent-events and @fig-recurrent-events) .

![Illustration of different types of time-to-event outcomes. Left: Standard single-event setting with transition from initial state (0) to state (1); Middle: Competing risks setting with $k$ competing events. Once one of the $\{1,\ldots, k\}$ events is observed, the others cannot be observed; Right: Multi-state setting where subjects can transition between multiple transient and terminal states with possible back-transitions.](Figures/survival/event-history-analysis.png){#fig-eha fig-alt="Schematic illustration of event history analysis."}


## Competing Risks {#sec-competing-risks}

In constrast to single-event survival analysis, competing risks are concerned with the time to the first of many, mutually exclusive events.
Mutually exclusive here means that once one of the events occurs, we can not observe the others (at the same time).
As in the single event case, the events may not necessarily be terminal (such as death), instead they just signify the end of the period of interest for a given observation.

Formally, let $Y$ be the time-to-event as before.
In the competing risks setting, there is now an additional random variable $E\in \{1,\ldots,k\}$ with realisations $e$, which denotes one of $k$ competing events that can occur at event time $Y$.
The survival outcome notation, $(T, \Delta)$ has to be extended to accomodate for the possibility of competing risks.
Previously, we defined the status indicator $\Delta \in \{0,1\}$ for right-censored data.
In the competing risks setting we have $\Delta = I(Y_i \leq C_I) \wedge E_i = e$, such that
$\Delta \in \{0, 1, \ldots, k\}$ where $\Delta = 0$ indicates censoring as before and $\Delta = e$ means the $e$th event occurred.

A common approach to competing-risks analysis is known as *cause-specific hazards*, where $h_{e}$ is defined as the hazard for the transition from initial state $0$ to state $e =1,\ldots,k$:

$$
h_{e}(\tau) = \lim_{\Delta \tau \to 0} \frac{P(\tau \leq Y \leq \tau + \Delta \tau, E = e\ |\ Y \geq \tau)}{\Delta \tau}, \; e = 1, \dots, k.
$$

As competing events are mutually exclusive at any time $\tau$, it is useful to further define the *all-cause hazard* which is the hazard of any event occuring:

$$
h(\tau) = \sum_{e = 1}^{k}h_{e}(\tau)
$$

the *all-cause cumulative hazard*

$$
H(\tau) = \int_{0}^\tau h(u)\ du = \sum_{e=1}^{k}\int_{0}^\tau h_{e}(u)\ du = \sum_{e=1}^k H_{e}(\tau)
$$

and the *all-cause survival probability*

$$
S(\tau) = P(Y > \tau) = \exp(-H(\tau))
$$

While notationally identical to the survival probability in the single-event case, the all-cause survival probability in the competing risks setting implies that *none* of the events occurred before $\tau$.
It is often not estimated directly but calculated from the cause specific hazards instead.

Another important quantity in competing risks analysis is the *Cumulative Incidence Function* (CIF), which denotes the probability of experiencing an event $e$ before time $\tau$

$$
F_{e}(\tau) = P(Y \leq \tau, E = e) = \int_{0}^\tau S(u)h_{e}(u)\ \mathrm{d}u.
$$

Intuitively the contributions in the integral consist of the probability of not experiencing any event before time $u$, $S(u)$, multiplied with the hazard of experiencing an event of type $e$, $h_{oe}(u)$ immediately at time $u$.
Calculating the CIF (in addition to the cause-specific hazards) is particularly important when making statements about the absolute risk (probability) for an event of type $e$, as it depends on all cause-specific hazards via $S(\tau)$.

This will be particularly relevant when assesing how features affect the probability for observing a specific event.
While some features might strongly affect some of the cause-specific hazards, if an event has overall low prevalence, then the absolute probability of observing the event will still be low.
Hence the CIF is useful for incorporating this information into an interpretable quantity.

<!-- To estimate the cause-specific hazards, an event-specific binary indicator is required, such that the indicator is $1$ if the event of interest is observed or $0$ for any other event, effectively treating them as censoring:
$$\delta_{ie} = \II(Y_i \leq C_i \wedge E_i = e) \in \{0, 1\},\ e=1,\ldots,k$$

With this definition, $k$ data sets $(t_i, \delta_{ie}, \bx_i)$, one for each of the $k$ events, can be fit to a separate model in order to obtain cause-specific hazards, as if in the single-event setting.
Once all hazards are estimated, the all-cause survival probability and CIFs can be calculated. -->

<!-- Following @beyersmann.competing.2012, this book assumes that the cause-specific hazards model fully describes the data generating processes and doesn't require an independence assumption for the competing events. -->



## Multi-state Models {#sec-multi-state}

Multi-state models can be considered the most general type of survival data, as other types (single-event, competing risks, recurrent events) can be viewed as special cases.

A common multi-state model, the illness-death model, is illustrated in @fig-multi-state, left panel.
The states are 'healthy' (State 0), with illness (State 1), or death (State 2).
Healthy subjects can transition directly to death ($0\rightarrow 1$) or after previous illness ($0\rightarrow 1 \rightarrow 2$), without the possibility of back-transitions.
Similar to competing risks, individual transitions are characterised by transition-specific hazards, denoted by $h_{\ell\rightarrow e}(\tau)$ or short $h_{\ell e}(\tau)$, where $\ell$ is the starting state and $e$ the end state  for a transition, $\ell, e \in \{0,\ldots,k\}$.
Remaining in the same state (transition into the same sate $h_{\ell\ell}(\tau)$) is equivalent to being censored for any transition possible from that state.

![Left: The illness-death model where subjects can transition from states: healthy (0), with illness (1), and terminal state death (2) without back-transitions. Right: Illustration of a general multi-state model with back-transitions. Here subjects can transition from state healthy (0) to different disease progressions (1, 2) with (partial) recovery (0, 1) and terminal state death (3).](Figures/survival/multi-state-examples-w-transitions.png){#fig-multi-state fig-alt="Schematic illustration of different multi-state models."}

The right panel of @fig-multi-state depicts a more general multi-state setting with back-transitions.
One can think of transitions between a healthy state (0) to different disease progressions (1, 2) with possibilty of improvement and recovery, and possible transition to a terminal state (3).

When modeling such data, interest often lies in estimation of the transition hazards, but also in transition probabilities $P_{\ell e}(\zeta, \tau)$, that is the probability to transition from state $\ell$ to $e$ between time points $\zeta$ and $\tau$ or state occupation probabilities $P_e(\tau)$, the probability to occupy state $e$ at time $\tau$.
Transition probabilities are often summarized in a matrix of transtion probabilities $\mathbf{P}(\zeta, \tau)$, where rows indicate starting states and columns indicate end states.

For example, for the illness-death model, the transition matrix would be given as

$$\mathbf{P}(\zeta, \tau) :=
  \begin{pmatrix}
  P_{00}(\zeta, \tau) & P_{01}(\zeta, \tau) & P_{02}(\zeta, \tau)\\
  \bullet & P_{11}(\zeta, \tau) & P_{12}(\zeta, \tau)\\
  \bullet & \bullet & P_{22}(\zeta, \tau)\\
  \end{pmatrix}.
$$

Here, the $\bullet$ indicate impossible transitions, as in the illness-death model there are no transitions from higher to lower states.



## Recurrent Events {#sec-recurrent-events}


Another setting in time-to-event data that might require special methods is the *recurrent events* setting, where the same event type can occur multiple times.
While the recurrent events setting can be viewed as a special case of the multi-state setting (@sec-multi-state), we treat it here separately as it can also be approached as single event data with correlation.
Some examples of recurrent events inlcude recurrence of infectious deseases, episodes of epilepsie, replacements of machine parts or episodes of chronic disease outbreaks.

@tbl-cgd-data shows data of chronic granolotomous disease (CGD) for two subjects.
Note the start-stop notation of the data that indicates the time in which a subject enters the risk set for the k*th* event number.
The columns $t_{start}$ and $t_{stop}$ indicate the times at which a subject is at risk for the $k$th outbreak.
The column $\delta$ indicates whether the subject experienced the $k$th outbreak or was censored.
Subject 1 for example experienced the first outbreak after 219 days, at which time it entered the risk set for event number 2.
The 2nd event was experienced at 373 days and the subject was censored for the 3rd event after 414 days.
This notation is equivalent to a multi-state representation of the recurrent events process, where each event number represents a different state.
In @fig-recurrent-events, right panenl, this is refered to as "Clock forward" approach.

| **ID**| $t_{start}$| $t_{stop}$|gap($t_{stop}-t_{start}$)|$\delta$| event number ($k$)|
|--:|---:|---:|------:|--:|-----:|
|  1|  0 | 219|    219| 1| 1|
|  1|219 | 373|    154| 1| 2|
|  1|373 | 414|     41| 0| 3|
|  7|  0 | 292|    292| 1| 1|
|  7|292 | 364|     72| 0| 2|
: Subset of the `cgd`  [@pkgsurvival] time-to-event dataset.
Rows are individual observation units ($ID$), $t_{start}$ and $t_{end}$ mark the beginning and end of "at risk time" for the $k$th event occurence, $\delta$ is the event indicator. {#tbl-cgd-data}

For recurrent events data without competing (terminal) event, however, the "Clock reset" approach (@fig-recurrent-events, left panel) is also popular. Instead of representing the data in the start-stop notation, the gap time is calculated instead (see fourth column in @tbl-cgd-data).
In this representation, we only consider how long the subject was at risk for the $k$th event, not at which time (on the calendar time scale).
It has the advantage that standard methods for analysis of single-event data can be used for modeling.
However, the resulting dependency between multiple data points from one subject (at risk for multiple events at the same time) needs to be taken into account in the modeling step.


![Illustration of transitions in the recurrent events setting. Left: "Clock reset" representation of recurrent events. Each time an event occurs, the clock is reset to 0 and we once again wait for occurence of an event (of the same type); Right: "Clock forward" representation. A subject transitions from 1st, to 2nd, etc. to $K$th event occurence](Figures/survival/recurrent-events.png){#fig-recurrent-events fig-alt="Schematic illustration of recurrent events transitions."}

The distribution of event recurrences per subject is often right-skewed in real data sets, which implies that there are only few events past event number $e^*$.
In practice, therefore, the data is often summarized such that we have event numbers $e = 1,\ldots, e^*_+$, where $e^*_+$ represents category "$e^*$ or higher".
