{{< include _setup.qmd >}}
# Symbols and Notation {.unnumbered}

{{< include _wip_minor.qmd >}}

The most common symbols and notation used throughout this book are presented below; in rare cases where different meanings are intended within the book, this will be made clear.

## Fonts, matrices, vectors

A lower-case letter in normal font, $x$, refers to a single, fixed observation.
When in bold font, a lower-case letter, $\xx$, refers to a vector of fixed observations, and an upper-case letter, $\XX$, represents a matrix.
Calligraphic letters, $\calX$, are used to denote sets.

A matrix will always be defined with its dimensions using the notation, $\XX \in \calX^{n \times p}$, or if for example $\calX$ is the set of Reals, it may be written as "$\XX$ is a $n \times p$ Real-valued matrix", analogously for integer-valued matrices etc.
By default, a 'vector' will refer to a column vector, which may be thought of as a matrix with $n$ rows and one column, and may be represented as:

$$
\xx = \begin{pmatrix}
        x_1 \\
        x_2 \\
        \vdots \\
        x_n
      \end{pmatrix}
$$

Vectors are usually defined using transpose notation, for example the vector above may instead be written as $\xx^\trans = (x_1 \ x_2 \cdots x_n)$ or $\xx = (x_1 \ x_2 \cdots x_n)^\trans$.
Vectors may also be defined in a shortened format as, $\xx \in \calX^n$, which implies a vector of length $n$ with elements as represented above.

A letter in normal font with one subscript refers to a single element from a vector.
For example, given $\xx \in \calX^n$, the $i$th element is denoted $x_i$.
Given a matrix $\XX \in \calX^{n \times p}$, a bold-face lower-case letter with a single subscript refers to the row of a matrix, for example the $i$th row would be $\xx_i = (x_{i;1} \ x_{i;2} \cdots x_{i;p})^\trans$.
Whereas a column is referenced with a semi-colon before the subscript, for example the $j$th column would be $\xx_{;j} = (x_{1;j} \ x_{2;j} \cdots x_{n;j})^\trans$.
Two subscripts can be used to reference a single element of a matrix, for example $x_{i;j}$ would be the element in the $i$th row and $j$th column of $\XX$.

## Functions

Typically, a 'hat', $\hat{x}$, will refer to the prediction or estimation of a variable, $x$, with bold-face used again to represent vectors.
A 'bar', $\bar{x}$, refers to the sample mean of $\xx$.
Capital letters in normal font, $X$, refer to scalar or vector random variables, which will be made clear from context.
$\EE(X)$ and $\Var(X)$ are the expectation and variance of the random variable $X$ respectively.
We write $A \indep B$, to denote that $A$ and $B$ are independent, i.e., that $P(A \cap B) = P(A)P(B)$.

A function $f$, will either be written as a formal map of domain to codomain, $f: \calX \rightarrow \calY; (x, y) \mapsto f(x, y)$ (which is most useful for understanding inputs and outputs), or more simply and commonly as $f(x, y)$.
Given a random variable, $X$, following distribution $\zeta$ (mathematically written $X \sim \zeta$), then $f_X$ denotes the probability density function, and analogously for other distribution defining functions.
In the survival analysis context (@sec-surv), a subscript "$0$" refers to a "baseline" function, for example, $S_0$ is the baseline survival function.

## Variables and acronyms

Common variables and acronyms used in the book are given in @tbl-not-var and @tbl-not-acr respectively.

| Variable | Definition |
| - | ---- |
| $\Reals, \PReals, \NNReals, \ExtReals$|Set of Reals, positive Reals (excl. zero), non-negative Reals (incl. zero), and Reals including $\pm\infty$. |
| $\PNaturals$|Set of Naturals excluding zero. |
| $(\XX, \tt, \dd)$ | Survival data where $\XX \in \Reals$ is a real-valued matrix of observations (rows) and features (columns), $\tt$ is a vector of observed outcome times, and $\dd$ is a vector of observed outcome indicators. |
| $\bb$|Vector of model coefficients/weights. |
| $\ee$ | Vector of linear predictors, $\dvec{\eta}{n}$, where $\ee = \XX\bb$ and $\eta_i = \xx_{i}^\trans\bb$. |
| $\calD, \dtrain, \dtest$| Dataset, training data, and testing data. |

: Common variables used throughout the book. {#tbl-not-var}

| Acronym | Definition |
| - | ---- |
| AFT | Accelerated Failure Time |
| cdf | Cumulative Distribution Function |
| chf | Cumulative Hazard Function |
| CPH | Cox Proportional Hazards |
| GBM | Gradient Boosting Machine |
| GLM | Generalised Linear Model |
| IPC(W) | Inverse Probability of Censoring (Weighted) |
| ML | Machine Learning |
| pdf | Probability Density Function |
| PH | Proportional Hazards |
| (S)SVM | (Survival) Support Vector Machine |
| t.v.i. | Taking Values In |

: Common acronyms used throughout the book. {#tbl-not-acr}
