::: {.content-visible when-format="html"}
{{< include _macros.tex >}}
:::

# Symbols and Notation {.unnumbered}

The most common symbols and notation used in this book are presented below, any deviations in the book will be made clear from context.

## Matrices and vectors

A lower-case letter in normal font, $x$, refers to a single, fixed observation.
When in bold font, a lower-case letter, $\xx$, refers to a vector of fixed observations, and an upper-case letter, $\XX$, represents a matrix.
Calligraphic letters, $\calX$, are used to denote sets.

A matrix will always be defined with its dimensions using the notation, $\XX \in \calX^{n \times p}$, or if for example $\calX$ is the set of real numbers, it may be written as "$\XX$ is an $n \times p$ real-valued matrix", analogously for matrices of integers, naturals, etc.
By default, a 'vector' will refer to a column vector, which may be thought of as a matrix with $n$ rows and one column, and may be represented as:

$$
\xx = \begin{pmatrix}
        x_1 \\
        x_2 \\
        \vdots \\
        x_n
      \end{pmatrix}
$$

Vectors are usually defined using transpose notation, for example the vector above may instead be written as $\xx^\trans = (x_1 \ x_2 \cdots x_n)$ or $\xx = (x_1 \ x_2 \cdots x_n)^\trans$.
Vectors may also be defined in a shortened format as $\xx \in \calX^n$, which implies a column vector of length $n$ with elements as represented above.

Let $\XX \in \calX^{n \times p}$ be a matrix.
A letter in normal font with two subscripts is used to reference a single element of a matrix, for example $x_{i,j} \in \calX$ would be the element in the $i$th row and $j$th column of $\XX$.
A bold-face, lower-case letter with a single subscript refers to a row of a matrix, for example $\xx_i = (x_{i,1} \ x_{i,2} \cdots x_{i,p})^\trans$; note that while $\xx_i$ refers to the row of a matrix, the column vector notation is maintained to adhere to the convention that vectors are column-vectors.
A column is referenced with a dot in place of the row index, for example the $j$th column of $\XX$ would be $\xx_{\cdot j} = (x_{1,j} \ x_{2,j} \cdots x_{n,j})^\trans$.
A letter in normal font with one subscript refers to a single element from a vector, for example given $\xx \in \calX^n$, the $i$th element is denoted $x_i$.

## Functions

A 'hat' over a variable, $\hat{x}$, will refer to the prediction or estimation of a variable, $x$, with bold-face used again to represent vectors.
A 'bar' over a variable, $\bar{x}$, refers to the sample mean of a corresponding vector $\xx$.
Capital letters in normal font, $X$, refer to scalar _or_ vector random variables, which will be made clear from context.
$\EE(X)$ is the expectation of the random variable $X$.

$g: \mathcal{A} \rightarrow \mathcal{B}$ denotes a function $g$ from some domain $\mathcal{A}$ to some codomain $\mathcal{B}$.
Whilst $f$ is often used to represent abstract functions, $g$ is primarily used in this book to avoid confusion with the probability density function.
Given a random variable $X$, $f_X$ denotes its probability density function; other distribution-defining functions are subscripted analogously, for example $F_X$ for the cumulative distribution function and $S_X$ for the survival function.
In the context of probability distributions, a subscript $0$ refers to a baseline function, for example, $S_0$ is the baseline survival function.

Let $B(\omega)$ be a logical statement, then $\II(B(\omega))$ denotes the indicator function, defined as

$$
\II(B(\omega))=
\begin{cases}
1, & \text{if } B(\omega) \text{ is true }, \\
0, & \text{otherwise.}
\end{cases}
$$ {#eq-example}

The exponential function, $e^x$, is written as $\exp(x)$, and $\log(x)$ refers to the natural logarithm $\ln(x) = \log_e(x)$.
When required, equations are referenced as a number in parentheses, for example the indicator function above is ([@eq-example]).

## Variables and acronyms

Common variables and acronyms used in the book are given in @tbl-not-var and @tbl-not-acr respectively.

| Variable | Definition |
| - | :---- |
| $\Reals, \PReals, \NNReals, \ExtReals$|Set of real numbers, positive real numbers, non-negative real numbers, and the extended real numbers (includes $\pm\infty$). |
| $\Naturals, \PNaturals$|Set of Naturals and positive Naturals. |
| $(\XX, \tt, \bsdelta)$ | Survival data where $\XX \in \Reals^{n \times p}$ is a real-valued matrix of $n$ observations (rows) and $p$ features (columns), $\tt \in \NNReals^n$ is a vector of observed outcome times, and $\bsdelta \in \Naturals^n$ is a vector of observed outcome indicators (generalized here for event-history analysis). |
| $\bsbeta$|Vector of model coefficients/weights, $\bsbeta \in \Reals^p$. |
| $\bseta$ | Vector of linear predictors, $\dvec{\eta}{n}$, where $\bseta = \XX\bsbeta$ and $\eta_i = \xx_{i}^\trans\bsbeta$. |
| $\calD, \dtrain, \dtest$| Dataset, training data, and testing data. |

: Common variables used throughout the book. {#tbl-not-var}

| Acronym | Definition |
| - | :---- |
| AFT | Accelerated Failure Time |
| CIF | Cumulative Incidence Function | 
| CPH | Cox Proportional Hazards |
| GBM | Gradient Boosting Machine |
| IPC(W) | Inverse Probability of Censoring (Weighting) |
| KM | Kaplan-Meier |
| NA | Nelson-Aalen |
| PH | Proportional Hazards |
| RMST | Restricted Mean Survival Time |
| RSF | Random Survival Forest |
| (S)SVM | (Survival) Support Vector Machine |

: Common acronyms used throughout the book. {#tbl-not-acr}
