---
abstract: TODO (150-200 WORDS)
---

::: {.content-visible when-format="html"}
{{< include _macros.tex >}}
:::

# Event-history Analysis {#sec-eha}

{{< include _wip.qmd >}}

___


In this chapter we take a more general view on time-to-event data.
So far, we only considered a single potentially censored, outcome of interest.
Here we explore more complex settings with multiple, potentially mutually exclusive events and recurrences of events.
In this generalisation, data is sometimes refered to *event-history data* and its analysis as *event-history analysis* (EHA).

One way to think about event history data is in terms of transitions between different states, as illustrated in @fig-eha.
Usually, a subject starts out in state 0 (for example, 'healthy') and transitions to different states from there.
States from which further transitions are possible are called *transient*, otherwise a state is called *terminal*.

In the *single event* setting (@fig-eha, left panel), a subject can only transition to one state (the event of interest).
This setting was the focus of @sec-surv.
There, the censoring event was considered independent of the event of interest.

In the *competing risks* setting (@fig-eha, upper right panel, @sec-competing-risks), a subject could transition to any of the $K$ mutually exclusive states, thus the subject is initially *at risk* for a transition to multiple states.
However, once one of them occurs, it is impossible to transition to another (for example, death from different causes).
In both cases, the event needs not be terminal, we just end the observation after the first occurence of an event.

In the most general case, the *multi-state* setting (@fig-eha lower right panel, see @sec-multi-state), there are multiple transient and terminal states with potential back transitions (for example, moving between different stages of an illness with the possibility of (partial) recovery and death as terminal event).

In the *recurrent events setting* (@sec-recurrent-events), the same event can be observed multiple times on the same subject (for example reccurrent respiratory infections during one year).

![Illustration of different types of time-to-event processes. Upper-left: Standard single-event setting with transition from initial state (0) to state (1); Upper-right: Competing risks setting with $k$ competing events. Once one of the $\{1,\ldots, k\}$ events is observed, the others cannot be observed anymore;
Lower-left: Recurrent events setting with multiple occurences of the same event. Lower-right: Multi-state setting where subjects can transition between multiple transient with possible back-transitions or to terminal states.](Figures/survival/event-history-analysis.png){#fig-eha fig-alt="Schematic illustration of event history analysis."}


## Competing Risks {#sec-competing-risks}

In constrast to single-event survival analysis, competing risks are concerned with the time to the first of multiple, mutually exclusive events.
Mutually exclusive here means that once one of the events occurs, we can not observe the others (at the same time).
As in the single event case, the events may not necessarily be terminal (such as death), instead they just signify the end of the period of interest for a given observation.
In contrast to the single event case, even if only one of the outcomes is of interest, the others can not be treated as independent censoring events.


For illustration consider the analysis of intensive care unit (ICU) patients described in [@beyersmann.competing.2012].
An excerpt of the data is given in @tbl-surv-data-sir.adm.
The endpoint of interest was time until death (`time`) with possible outcomes 0 (right-censoring at the end of the study), 1 (discharge alive), or 2 (death on ICU).
The interest was in how pneumonia status at admission to the ICU (`pneu`: 0 = no, 1 = yes) affects mortality.

|    `id`| `time`| `status`| `pneu`|
|-------:|----:|------:|----:|
|   31561|    8|      0|    0|
|   31205|    8|      0|    0|
| 2002453|   31|      1|    1|
| 1021616|    5|      1|    0|
| 1014059|    9|      2|    0|
| 1003059|    5|      2|    0|

: Subset of the `sir.adm` dataset [@pkgmvna].
Rows are individual observations (`id`), `time` is time under observation, `status` indicates the outcome observed (0=censored at the end of the study, 1=discharged alive from the ICU, 2: death in the ICU). {#tbl-surv-data-sir.adm}

Here, discharge from the hospital must not be considered independent right-censoring as was the case in the `tumor` data example in @sec-surv-km.
There, patients were followed even after hospital discharge, thus loss to follow-up could be considered truly independent of the event of interest.
In this study on the other hand, follow-up stopped once patients were discharged and it is unrealistic to assume that subjects would continue to be exposed to the same risk of dying after discharge compared to subject still in the ICU.


Formally, let $Y$ be the time-to-event as before.
In the competing risks setting, there is now an additional random variable $E\in \{1,\ldots,k\}$ with realisations $e$, which denotes one of $k$ competing events that can occur at event time $Y$.
The survival outcome notation, $(T, \Delta)$ has to be extended to accomodate for the possibility of competing risks.
Previously, we defined the status indicator $\Delta \in \{0,1\}$ for right-censored data.
In the competing risks setting we have $\Delta = I(Y_i \leq C_i) \wedge E_i = e$, such that
$\Delta \in \{0, 1, \ldots, k\}$ where $\Delta = 0$ indicates censoring as before (that is subject remained in state 0 until end of follow up) and $\Delta = e$ means the $e$th event occurred.
Rather then estimating the distribution of event times $P(Y\leq \tau)$, the goal is to estimate the joint distribution of $Y$ and $E$, $P(Y\leq \tau, E=e)$.

A common approach to competing-risks analysis is known as *cause-specific hazards*, where $h_{e}$ is defined as the hazard for the transition from initial state $0$ to state $e =1,\ldots,k$:
<!--  -->
$$
h_{e}(\tau) = \lim_{\triangle \tau \to 0} \frac{P(\tau \leq Y \leq \tau + \triangle \tau, E = e\ |\ Y \geq \tau)}{\triangle \tau}, \; e = 1, \dots, k.
$$ {#eq-cause-specific-hazard}
<!--  -->

Analogous to the singl-event case, we can also define the cause-specific cumulative hazard
<!--  -->
$$
H_{e}(\tau) = \int_{0}^\tau h_e(u)\ du
$$ {#eq-cause-specific-cumu-hazard}
<!--  -->

As competing events are mutually exclusive at any time $\tau$, it is possible to define the *all-cause hazard* which is the hazard of any event occuring as the sum of all cause-specific hazards
<!--  -->
$$
h(\tau) = \sum_{e = 1}^{k}h_{e}(\tau),
$$ {#eq-all-cause-hazard}
<!--  -->
as well as the *all-cause cumulative hazard*, which can be obtained either via the integral over the all-cause hazard (@eq-all-cause-hazard) or as sum of cause-specific cumulative  hazards (@eq-cause-specific-cumu-hazard):
<!--  -->
$$
H(\tau) = \int_{0}^\tau h(u)\ du = \sum_{e=1}^{k}\int_{0}^\tau h_{e}(u)\ du = \sum_{e=1}^k H_{e}(\tau).
$$ {#eq-all-cause-cumu-hazard}
<!--  -->
The *all-cause survival probability*
<!--  -->
$$
S(\tau) = P(Y > \tau) = \exp(-H(\tau))
$$ {#eq-all-cause-surv-prob}
<!--  -->
gives the probability that *none* of the events occurred before $\tau$.
It is usually not estimated directly but calculated from the cause specific hazards instead via @eq-all-cause-cumu-hazard and @eq-all-cause-surv-prob. Thus, estimation of the cause-specific hazards (@eq-cause-specific-hazard) fully determines the joint distribution of $Y$ and $E$.


In applications, next to the cause-specific (cumulative) hazards, one is often interested in the *Cumulative Incidence Function* (CIF), which denotes the probability of experiencing an event $e$ before time $\tau$
<!--  -->
$$
F_{e}(\tau) = P(Y \leq \tau, E = e) = \int_{0}^\tau S(u-)h_{e}(u)\ \mathrm{d}u,\ e\in \{1,\ldots,k\},
$$ {#eq-cif}
<!--  -->
where

* $S(u-)$ is the probility of surviving (not experiencing any of the competing events) until the time-point shortly before $u$
* $S(u-)h_{e}(u)$ (@eq-continuous-hazard) is the probability of experiencing event $e$ at time point $u$.

$F_e(\tau)$ can be interpreted as the proportion of subjects who experienced event of type $e$ until time $\tau$.
Because the events are mutually exclusive, it holds that $F(\tau) = P(Y\leq\tau) = \sum_{e=1}^k F_e(\tau) = 1 - S(\tau)$.


## Aalen-Johanson estimator

As for the single-event case (@sec-surv-estimation-non-param), one can define a simple non-parametric estimator for the cause-specific cumulative hazard (@eq-cause-specific-cumu-hazard) based on a generalization of the Nelson-Aalen estimator (@eq-nelson-aalen) and the Aalen-Johanson estimator (@aalenEmpiricalTransitionMatrix1978) for the CIf (@eq-cif).

Recall from the definitions of the unique ordered event times $t_{(k)}, k=1\ldots,m$, risk-set at time $t_{(k)}$, $\calR_{t_{(k)}}$, number of events $d_{t_{(k)}}$ and number at risk $n_{t_{(k)}}$ from @sec-data-rc.

The Nelson-Aalen estimator for the cause-specific cumulative hazard is given by updating the numerator $d_{t_{(k)}}$ to $d_{e,t_{(k)}}$ the number of events of type $e$ at time $t_{(k)}$, such that

$$
\hat{H}_{NA,e}(\tau) = \sum_{k:t_{(k)} \leq \tau} \frac{d_{e,t_{(k)}}}{n_{t_{(k)}}}
$$ {#eq-cs-nelson-aalen}


The all-cause survival probability follows from @eq-all-cause-cumu-hazard and @eq-all-cause-surv-prob as

$$
\hat{S}(\tau) = \exp\left(-\sum_{e=1}^k \hat{H}_{NA,e}\right)
$$

and the Aalen-Johanson (AJ) estimator for the CIF as

$$
\hat{F}_{AJ,e}(\tau) = \hat{P}(Y\leq \tau, E=e) = \sum_{k:t_{(k)}\leq \tau} \hat{S}(\tau-)\frac{d_{e,t_{(k)}}}{n_{t_{(k)}}}
$$ {#eq-aalen-johanson}


To see the connection of @eq-aalen-johanson to @eq-cif, note that $\frac{d_{e,t_{(k)}}}{n_{t_{(k)}}}=\hat{P}(Y\in (t_{(k-1)},t_{(k)}], E=e|Y \geq t_{(k-1)})$ is an estimate of the cause-specific version of the discrete time hazard (@eq-discrete-hazard). Thus

$$
\hat{S}(\tau-)\frac{d_{e,t_{(k)}}}{n_{t_{(k)}}} = \hat{P}(Y > t_{(k-1)})\hat{P}(Y\in (t_{(k-1)},t_{(k)}], E=e|Y \geq t_{(k-1)})
$$







For illustration, re-consider the data from @tbl-surv-data-sir.adm. Recall that one is interested in estimation of the mortality conditional on pneumonia status at admission, while accounting for discharge from the ICU as competing risk ($E \in \{\text{"discharge"}, \text{"death"}\}$). @fig-cif-sir shows the AJ estimates of the CIFs for each event (discharge/death) separately for patients with and without pneumonia. Examplary, the proportion of subjects with pneumonia being discharged until $\tau=120\text{ days}$ is approximately 75% ($\hat{F}_{\text{discharge}}(120) = P(Y\leq 120, E=\text{"discharge"})\approx 0.75$), while approximately 25% died in the ICU ($\hat{F}_{\text{death}}(120) = P(Y\leq 120, E=\text{"death"}))\approx 0.25$. For patients without pneumonia we have $\hat{F}_{\text{discharge}}(120) \approx 0.91$ and $\hat{F}_{\text{death}} \approx 0.09$.
In this example $\hat{F}_{\text{discharge}} + \hat{F}_{\text{death}} \approx 1$ for both pneumonia groups, as only 14 of 747 patients were censored at the end of the follow-up (that is neither died or were discharged).

![Aalen-Johanson estimator for the `sir.adm` data [@pkgmvna], stratified by pneumonia status at admission to the ICU. Left panel: Proportion of subjects discharged alive from the ICU. Right panel: Proportion of subjects who died in the ICU.](Figures/survival/cif-sir.png){#fig-cif-sir fig-alt="Illustration of the Aalen-Johanson estimator for the cumulative incidence function, stratified by pneumonia status at admission to the ICU."}



For now, let's assume that discharge alive indicates independent right-censoring. Under this assumption, we could use $\hat{F}(\tau, E=\text{"death"}) = \hat{F}(\tau) = 1-\hat{S}_{KM}$, where $\hat{S}_{KM}$ is the Kaplan-Meier estimator (@sec-surv-km).









## Multi-state Models {#sec-multi-state}

Multi-state models can be considered the most general type of survival data, as other types (single-event, competing risks, recurrent events) can be viewed as special cases.

A common multi-state model, the illness-death model, is illustrated in @fig-multi-state, left panel.
The states are 'healthy' (State 0), with illness (State 1), or death (State 2).
Healthy subjects can transition directly to death ($0\rightarrow 1$) or after previous illness ($0\rightarrow 1 \rightarrow 2$), without the possibility of back-transitions.
Similar to competing risks, individual transitions are characterised by transition-specific hazards, denoted by $h_{\ell\rightarrow e}(\tau)$ or short $h_{\ell e}(\tau)$, where $\ell$ is the starting state and $e$ the end state  for a transition, $\ell, e \in \{0,\ldots,k\}$.
Remaining in the same state (transition into the same sate $h_{\ell\ell}(\tau)$) is equivalent to being censored for any transition possible from that state.

![Left: The illness-death model where subjects can transition from states: healthy (0), with illness (1), and terminal state death (2) without back-transitions. Right: Illustration of a general multi-state model with back-transitions. Here subjects can transition from state healthy (0) to different disease progressions (1, 2) with (partial) recovery (0, 1) and terminal state death (3).](Figures/survival/multi-state-examples-w-transitions.png){#fig-multi-state fig-alt="Schematic illustration of different multi-state models."}

The right panel of @fig-multi-state depicts a more general multi-state setting with back-transitions.
One can think of transitions between a healthy state (0) to different disease progressions (1, 2) with possibilty of improvement and recovery, and possible transition to a terminal state (3).

When modeling such data, interest often lies in estimation of the transition hazards, but also in transition probabilities $P_{\ell e}(\zeta, \tau)$, that is the probability to transition from state $\ell$ to $e$ between time points $\zeta$ and $\tau$ or state occupation probabilities $P_e(\tau)$, the probability to occupy state $e$ at time $\tau$.
Transition probabilities are often summarized in a matrix of transtion probabilities $\mathbf{P}(\zeta, \tau)$, where rows indicate starting states and columns indicate end states.

For example, for the illness-death model, the transition matrix would be given as

$$\mathbf{P}(\zeta, \tau) :=
  \begin{pmatrix}
  P_{00}(\zeta, \tau) & P_{01}(\zeta, \tau) & P_{02}(\zeta, \tau)\\
  \bullet & P_{11}(\zeta, \tau) & P_{12}(\zeta, \tau)\\
  \bullet & \bullet & P_{22}(\zeta, \tau)\\
  \end{pmatrix}.
$$

$\bullet$ indicates impossible transitions, as in the illness-death model there are no transitions from higher to lower states.



## Recurrent Events {#sec-recurrent-events}

The *recurrent events* setting is defined by the same event type occurring multiple times.
While the recurrent events setting can be viewed as a special case of the multi-state setting (@sec-multi-state), we treat it here separately as it can also be approached as single event data with correlation.
Some examples of recurrent events include recurrence of infectious diseases, episodes of epilepsy, and replacements of machine parts.

@tbl-cgd-data shows data of chronic granolotomous disease (CGD) for two subjects.
Note the start-stop notation of the data ($t_{start}, t_{stop}$ respectively) that indicates the time in which a subject enters the risk set for the k*th* event number.
The column $\delta$ indicates whether the subject experienced the $k$th outbreak or was censored.
For example, Subject 1 (first three rows) experienced the first outbreak (first row) after 219 days, at which time they entered the risk set for event number 2.
The second event (second row) was experienced at 373 days and the subject was then censored for the third event (third row) after 414 days.
This notation is equivalent to a multi-state representation of the recurrent events process, where each event number represents a different state.
In @fig-recurrent-events, right panel, this is refered to as "Clock forward" approach.

| ID| $k$ | $t_{start}$| $t_{stop}$|$\delta$|$gap$|
|--:|---:|---:|------:|--:|-----:|
|  1|1|  0 | 219|   1| 219| 
|  1|2|219 | 373|   1| 154| 
|  1|3|373 | 414|   0|  41| 
|  7|1|  0 | 292|   1| 292| 
|  7|2|292 | 364|   0|  72| 
: Subset of the `cgd`  [@pkgsurvival] time-to-event dataset.
Rows are individual observation units ($ID$), $k$ is the $k$th event occurrence, $t_{start}$ and $t_{stop}$ mark the beginning and end of the "at risk time" for the $k$th event occurence, $\delta$ is the event indicator and $gap = t_{stop} - t_{start}$. {#tbl-cgd-data}

For recurrent events data without competing (terminal) events, the "Clock reset" approach (@fig-recurrent-events, left panel) can be used.
Instead of representing the data in the start-stop notation, the gap time is calculated instead (see fourth column in @tbl-cgd-data).
In this representation, we only consider how long the subject was at risk for the $k$th event, not at which time (on the calendar time scale).
It has the advantage that standard methods for analysis of single-event data can be used for modeling.
However, the resulting dependency between multiple data points from one subject (at risk for multiple events at the same time) needs to be taken into account in the modeling step.

![Illustration of transitions in the recurrent events setting. Left: "Clock reset" representation of recurrent events. Each time an event occurs, the clock is reset to 0 and we once again wait for occurence of an event (of the same type); Right: "Clock forward" representation. A subject transitions from 1st, to 2nd, etc. to $K$th event occurence](Figures/survival/recurrent-events.png){#fig-recurrent-events fig-alt="Schematic illustration of recurrent events transitions."}

The distribution of event recurrences per subject is often right-skewed in real data sets, which implies that there are only few events past event number $e^*$.
In practice, therefore, the data is often summarized such that we have event numbers $e = 1,\ldots, e^*_+$, where $e^*_+$ represents category "$e^*$ or higher".



## Estimation

As in @sec-surv