---
abstract: "This chapter introduces scoring rules as measures for evaluating probabilistic predictions in survival analysis, with a focus on assessing overall predictive performance through calibration and discrimination. The chapter first reviews scoring rules in classification settings, introducing concepts such as properness and strict properness through the Brier score and log loss. These ideas are then extended to censored survival data, where survival losses are formalized and their dependence on censoring assumptions is discussed. Common survival scoring rules are presented, including the integrated survival Brier score, right-censored log loss, and integrated survival absolute score, with attention given to their interpretation, weighting schemes, and theoretical properties. Particular emphasis is placed on the integrated survival Brier score and logarithmic losses, including discussion of properness and practical limitations. Prediction error curves are introduced as graphical tools for time-dependent evaluation, while baseline models and explained residual variation are discussed to improve interpretability of scores. The chapter concludes by considering extensions to competing risks settings and highlighting ongoing methodological challenges, including limited consensus regarding optimal scoring rule selection and practical implementation constraints."
---

::: {.content-visible when-format="html"}
{{< include _macros.tex >}}
:::

# Scoring Rules {#sec-rules}

Scoring rules\index{scoring rules} evaluate probabilistic predictions and (attempt to) measure the overall predictive ability of a model in terms of both calibration\index{calibration} and discrimination\index{discrimination} [@Gneiting2007; @Murphy1973].
In contrast to calibration measures, which assess the average performance across all observations on a population level, scoring rules evaluate the sample mean of individual predictions across all observations in a test set.
As well as being able to provide information at an individual level, scoring rules are also popular as probabilistic forecasts are widely recognized to be superior to deterministic predictions for capturing uncertainty in predictions [@Dawid1984; @Dawid1986].
Formalization and development of scoring rules has primarily been due to Dawid [@Dawid1984; @Dawid1986; @Dawid2014] and Gneiting and Raftery [@Gneiting2007]; though the earliest measures promoting "rational" and "honest" decision making date back to the 1950s [@Brier1950; @Good1952].
Few scoring rules have been proposed in survival analysis, although the past few years have seen an increase in popularity in these measures.
Before delving into these measures, we will first describe scoring rules in the simpler classification setting.\index{Brier score}\index{log loss}

Scoring rules are pointwise losses, which means a loss is calculated for all observations and the sample mean is taken as the final score.
Each scoring rule is therefore introduced for a single observation $i$ only.
To simplify notation, let $\hatS_i$ be a shorthand for the survival function prediction for observation $i$, usually written as $\hatS(\cdot \mid \xx_i)$.
As other distribution defining functions can be derived from the survival function, only $\hatS_i$ is included in function signatures.
As usual, $(t_i, \delta_i)$ is the observed survival outcome.

## Classification losses

In the simplest terms, a scoring rule compares a probabilistic prediction to an observed outcome and assigns them a score.
Formally, a loss function is written as

$$
L: \calP \times \calY \to \ExtReals,
$$

where $p \in \calP$ is a (predicted) probability distribution over the outcome space $\calY$ and $Y$ is a random variable representing the ground truth.
In classification tasks, $\calY \subseteq \Naturals$.

As an example, take the Brier score [@Brier1950] defined by:\index{Brier score}
$$
L_{Brier}(\hatp_i, y_i) = (y_i - \hatp_i(y_i))^2
$$

For a binary classification problem, $\hatp_i$ is a predicted probability mass function such that $\hatp_i(x) \in [0,1]$ and $y_i \in \{0,1\}$ is the ground truth.\index{classification!binary}
This is intuitive: if the event occurs and $y_i = 1$, then $\hatp_i(y_i)$ should be as close to one as possible to minimize the loss.
On the other hand, if $y_i = 0$ then the better prediction would be $\hatp_i(y_i) = 0$.

This demonstrates an important property of the scoring rule, *properness*.\index{scoring rules!proper}
A loss is *proper* if it is minimized by the correct prediction.
In contrast, the loss $L_{improper}(\hatp_i, y_i) = 1 - L_{Brier}(\hatp_i, y_i)$ is still a scoring rule as it compares the ground truth to the prediction probability distribution, but it is clearly improper as the perfect prediction ($\hatp_i(y_i) = y_i$) would result in a score of $1$ whereas the worst prediction would result in a score of $0$.
Proper losses provide a method of model comparison as, by definition, predictions closest to the true distribution will result in lower expected losses.

Another important property is *strict* properness.\index{scoring rules!strictly proper}
A loss is *strictly proper* if the loss is uniquely minimized by the 'correct' prediction.
For example, the Brier score is minimized by only one value, which is the optimal prediction [@fig-eval-brierlog].
Strictly proper losses are particularly important for automated model optimization, as minimization of the loss will result in the 'optimum score estimator based on the scoring rule' [@Gneiting2007].

Mathematically, a classification loss $L: \calP \times \calY \rightarrow \ExtReals$ is *proper* if for any distributions $p_Y,p$ in $\calP$ and for any random variables $Y \sim p_Y$ (with observations $y_i$), it holds that $\EE[L(p_Y, Y)] \leq \EE[L(p, Y)]$.
The loss is *strictly proper* if, in addition, $p = p_Y$ uniquely minimizes the loss.

As well as the Brier score, which was defined above, another widely used loss is the log loss [@Good1952], defined by\index{log loss}

$$
L_{logloss}(\hatp_i, y_i) = -\log \hatp_i(y_i)
$$ {#eq-logloss}

where again $y_i \in \{0,1\}$ is the ground truth and $\hatp_i$ is a predicted probability distribution.

These losses are visualized in @fig-eval-brierlog, which highlights that both losses are strictly proper [@Dawid2014] as they are minimized when the true prediction is made, and converge to the minimum as predictions are increasingly improved.
It can also be seen from the scale of the plots that the log loss penalizes wrong predictions more strongly than the Brier score, which may be beneficial or not depending on the given use-case.

![Brier and log loss scoring rules for a binary outcome and varying probabilistic predictions. x-axis is a probabilistic prediction in $[0,1]$, y-axis is Brier score (left) and log loss (right). Blue lines are varying Brier score/log loss over different predicted probabilities when the true outcome is 1. Red lines are varying Brier score/log loss over different predicted probabilities when the true outcome is 0. Both losses are minimized when $\hatp_i(y_i) = y_i$.](Figures/evaluation/brier_logloss.png){#fig-eval-brierlog fig-alt="Left plot (x=Brier score, y = predicted probability), shows two crossing curves, a blue curve (when y_i=1) from (0,1) to (1,0) and a red curve (when y_i=0) from (0,0) to (1,1). Right plot (x=Log loss, y = predicted probability), shows two crossing curves, a blue curve (when y_i=1) from (0,3) to (1,0) and a red curve (when y_i=0) from (0,0) to (1,3). "}

## Survival losses {#sec-eval-distr-commonsurv}

Analogously to classification losses, one can define a survival loss as\index{survival loss}

$$
L_S: \calP \times \calT \times \bset \rightarrow \ExtReals,
$$

where now $\calP$ denotes a set of probability distributions over $\PReals$ and $\calT \subseteq \PReals$.
For any distributions $p_Y, p$ in $\calP$, $L_S$ is called:

* **proper** if $\EE_{T, \Delta} [L_S(p_Y, T, \Delta)] \le \EE_{T,\Delta}[L_S(p, T, \Delta)]$ for all $p \in \calP$;
* **strictly proper** if in addition to being proper, $p = p_Y$ uniquely minimizes the loss.

With these definitions, the rest of this chapter lists common scoring rules in survival analysis and discusses some of their properties.
As with other chapters, this list is not exhaustive but will cover commonly used losses.
The losses are grouped into squared losses, absolute losses, and logarithmic losses, which respectively estimate the mean squared error, mean absolute error, and log loss in uncensored settings.

:::: {.callout-note icon=false}

## Box 3  (Estimating IPC weights)

Inverse probability of censoring weighting (IPCW)\index{inverse probability of censoring weights} is used to account for removal of censored observations (@sec-surv-ipcw).
For discrimination measures (@sec-eval-crank), there appears to be broad consensus around weighting schemes based on nonparametric estimators, namely the Kaplan-Meier estimator.\index{Kaplan-Meier estimator}
For scoring rules, there is less consensus about how the censoring distribution should be estimated.
Common approaches include:

1. Nonparametric estimators --- For example, the Kaplan-Meier estimator may be used to estimate the marginal censoring distribution. This is likely the oldest and most commonly used approach and assumes censoring is marginally independent of the event time; 
2. Fitted survival models --- A secondary survival model, such as the Cox PH, is fitted to the censoring distribution. This may account for censoring that is conditionally independent of the event time;
3. Joint or iterative estimation --- A censoring model is estimated alongside the event model, most commonly in approaches such as boosting\index{boosting} (@sec-boost) and neural networks\index{neural networks} (@sec-nnet). This allows flexible censoring models but introduces additional modelling assumptions.

The nonparametric approach is simple and widely used, but may lead to biased estimators when censoring depends on covariates.
Model-based estimates may account for such censoring mechanisms, but their validity depends on assumptions about the censoring model.
In practice, these models are typically assumed to be correctly specified rather than independently validated.
When this assumption is violated and the censoring model is misspecified, bias may be introduced into the resulting measure.
This therefore creates an additional modelling problem, as the validity of IPCW depends on assumptions about the censoring distribution.

In predictive settings, the ranks induced by losses are often more important than their absolute values.
In such settings, (strict) properness may be more relevant for model comparison and optimization than consistency guarantees.
In practice, software implementations often allow flexibility in how the censoring distribution is estimated, and the relative merits of these approaches are not discussed further here.

Throughout this chapter, $\hatG(\cdot)$ denotes an estimate of the censoring survival distribution, whether obtained nonparametrically or via a fitted model.

::::

### Squared losses {#sec-rules-squared}

The Integrated Survival Brier Score (ISBS)\index{integrated survival Brier score} was introduced by Graf [@Graf1995; @Graf1999] as an analogue to the integrated Brier score in regression.
It is likely the most commonly used scoring rule in survival analysis, possibly due to its intuitive interpretation.

The loss is defined by

$$
\begin{split}
L_{ISBS}(\tau^*, \hatS_i, t_i, \delta_i \mid \hatG) = \int^{\tau^*}_0  \frac{\hatS_i^2(\tau) \II(t_i \leq \tau, \delta_i=1)}{\hatG(t_i)} + \frac{\hatF_i^2(\tau) \II(t_i > \tau)}{\hatG(\tau)} \ d\tau
\end{split}
$$ {#eq-igs}

where  $\hatS_i^2(\tau) = (\hatS_i(\tau))^2$ and $\hatF_i^2(\tau) = (1 - \hatS_i(\tau))^2$, and $\tau^* \in \PReals$ is an upper threshold to compute the loss up to, and $\hatG$ is the IPC weighting (Box 3).

At first glance this might seem intimidating but it is worth taking the time to understand the intuition behind the loss.
Recall the classification Brier score, $L(\hatp_i, y_i) = (y_i - \hatp_i(y_i))^2$; this provides a method to evaluate a probability mass function at one point.
In a regression setting, the *integrated Brier score*\index{integrated Brier score}, also known as the continuous ranked probability score, is the integral of the Brier score for all real-valued thresholds [@Gneiting2007] and hence allows predictions to be evaluated over multiple points as:

$$
L(\hatF_i, y_i) = \int (\II(y_i \leq \tau) - \hatF_i(\tau))^2 \dtau,
$$ {#eq-crps}

where $\hatF_i$ is the predicted cumulative distribution function and $\tau$ is some meaningful threshold.
As the left-hand indicator can only take one of two values, @eq-crps can be represented as two distinct cases, now using $t$ instead of $y$ to represent time:

$$
L(\hatF_i, t_i) =
\begin{cases}
(1 - \hatF_i(\tau))^2 = \hatS_i^2(\tau), & \text{ if } t_i \leq \tau \\
(0 - \hatF_i(\tau))^2 = \hatF_i^2(\tau), & \text{ if } t_i > \tau
\end{cases}
$$ {#eq-graf-cases}

In the first case, the observation experienced the event before $\tau$, hence the optimal prediction for $\hatF_i(\tau)$ (the probability of experiencing the event before $\tau$) is $1$, and therefore the optimal $\hatS_i(\tau)$ is $0$.
Conversely, in the second case where the observation has not experienced the event, the optimal $\hatF_i(\tau)$ is $0$.
The loss therefore meaningfully represents the ideal predictions in the two possible real-world scenarios.

The final component of the loss is accommodating for censoring.
At $\tau$ an observation will either have:

1. Not experienced any outcome: $t_i > \tau$;
2. Experienced the event: $t_i \leq \tau \wedge \delta_i = 1$; or
3. Been censored: $t_i \leq \tau \wedge \delta_i = 0$

Censored observations are discarded after the censoring time as evaluating predictions after this time is impossible as the ground truth is unknown.
To compensate for removing observations, IPCW\index{inverse probability of censoring weights} (@sec-cindex) is again used to upweight predictions as $\tau$ increases.
IPC weights, $W_i$ are defined such that observations are either weighted by $\hatG(\tau)$ when they have not yet experienced the event or by their final observed time, $\hatG(t_i)$, otherwise (@tbl-ipcw-weights).

| $W_i := W(t_i, \delta_i)$ | $t_i > \tau$ | $t_i \leq \tau$ |
| - | - | - |
| $\delta_i = 1$ | $\hatG^{-1}(\tau)$ | $\hatG^{-1}(t_i)$ |
| $\delta_i = 0$ | $\hatG^{-1}(\tau)$ | $0$ |
: IPC weighting scheme for the ISBS. {#tbl-ipcw-weights}

When censoring is fully independent, the Graf score consistently estimates the mean square error\index{mean square error} [@Gerds2006].
Despite this, the score is not strictly proper and even its properness is in doubt (in doubt not proven due to there being an open debate in the literature about how to define properness in a survival context) [@Rindt2022].
Fortunately, as the score is deeply embedded in the literature, experiments have demonstrated that scores generated from using the ISBS only differ very slightly from a strictly proper alternative [@Sonabend2025].

There has not been significant development in extending squared losses to handle other forms of censoring and truncation, though one notable extension is an adaptation of the ISBS for administrative censoring [@Kvamme2023].
There is also some, but sparse, research into extending the ISBS to handle interval censoring by estimating the probability of survival within the interval [@Tsouprou2015], however there is no evidence of use in practice.

### Logarithmic losses {#sec-rules-log}

The development of logarithmic losses follows from adapting the negative log-likelihood for censored datasets.
Consider the usual negative log-likelihood in a regression setting, which is a standard measure for evaluating a model's performance:\index{negative log-likelihood}

$$
L_{NLL}(\hatf_i, y_i) = -\log[\hatf_i(y_i)]
$$

for a predicted density function $\hatf_i$ and true outcome $y_i$.
Note this is analogous to the classification log loss in (@eq-logloss) with the probability mass function replaced with the density function.

Now recall (@eq-objective-function) from @sec-surv-estimation-param, which gives the contribution from a single observation as:

$$
\mathcal{L}(t_i) \propto
\begin{dcases}
f(t_i), & \text{ if $i$ is uncensored } \\
S(t_i), & \text{ if $i$ is right-censored } \\
F(t_i), & \text{ if $i$ is left-censored } \\
S(l_i)-S(r_i), & \text{ if $i$ is interval-censored } \\
\end{dcases},
$$

where $r_i, l_i$ are the boundaries of the censoring interval (adaptations in the presence of left-truncation as described in @sec-surv-estimation-param may also be applied).

The log loss can then be constructed depending on what type of censoring or truncation is present in the data.
For example, if only right-censoring is present then the right-censored log loss (RCLL) is defined as:\index{right-censored log loss}

$$
L_{RCLL}(\hatS_i, t_i, \delta_i) = -\log\big(\delta_i\hatf_i(t_i) + (1-\delta_i)\hatS_i(t_i)\big),
$$ {#eq-rcll}

where $\hatf_i$ is derived from $\hatS_i$ (@sec-distributions-continuous).

If censoring is independent of the event (@sec-types-of-censoring) then this scoring rule is strictly proper [@Avati2020].
The loss is also highly interpretable as a measure of predictive performance when broken down into its two halves:

1. An observation censored at $t_i$ has not experienced the event and hence the ideal prediction would be close to $\hatS_i(t_i) = 1$; correspondingly (@eq-rcll) means the loss is minimized for censored observations at $-\log(1) = 0$.
2. If an observation experiences the event at $t_i$, then the ideal prediction would correspond to $\hatf_i(t_i) \rightarrow \infty$ and therefore $L_{RCLL}(\hatS_i, t_i, \delta_i=1) \rightarrow -\infty$.

While censored observations contribute non-negative losses only, for uncensored observations the loss is unbounded below in continuous time.
This means uncensored observations can theoretically contribute more extreme loss values than censored ones.
In practice, many survival models predict $\hatS_i \in [0,1]$, from which $\hatf_i$ is numerically derived (@tbl-dist-transformations).
Under these approximations, density frequently lie in $[0,1]$ making strongly negative losses uncommon.

Analogous losses to (@eq-rcll) follow when left- and/or interval-censoring is present by using the objective functions in @sec-surv-estimation-param.

Other logarithmic losses have also been proposed, such as the integrated survival log loss (ISLL)\index{integrated survival log loss} in @Graf1999.
The ISLL is similar to the ISBS except $\hatS_i^2$ and $\hatF_i^2$ are replaced with $\log(\hatS_i)$ and $\log(\hatF_i)$ respectively. 
To our knowledge, the ISLL does not appear used in practice and nor is there a practical benefit over other losses -- though we note the work of @Alberge2025 discussed in @sec-rules-ext.

### Absolute losses

The final class of losses considered here can be viewed as analogs of the mean absolute error in an uncensored setting.
The integrated survival absolute score (ISAS)\index{integrated survival absolute score}, developed over time by @Schemper2000 and @Schmid2011 is similar to the ISBS but removes the squared term:

$$
L_{ISAS}(\hatS_i, t_i, \delta_i \mid \hatG) = \int^{\tau^*}_0 \frac{\hatS_i(\tau)\II(t_i \leq \tau, \delta_i = 1)}{\hatG(t_i)} + \frac{\hatF_i(\tau)\II(t_i > \tau)}{\hatG(\tau)} \ d\tau
$$

where $\hatG$ and $\tau^*$ are as defined above.
Analogously to the ISBS, the ISAS consistently estimates the mean absolute error when censoring is fully independent [@Schmid2011], but there are also no proofs or claims of properness.
The ISAS and ISBS tend to yield similar results [@Schmid2011], but in practice the former does not appear to be widely used.

## Prediction error curves {#sec-pecs}

As well as evaluating probabilistic outcomes with integrated scoring rules, non-integrated scoring rules can be utilized for evaluating distributions at a single point.
For example, instead of evaluating a probabilistic prediction with the ISBS over $\PReals$, one could compute the Brier score at a single time-point, $\tau \in \PReals$, only.
Plotting these for varying values of $\tau$ results in *prediction error curves*, which provide a simple visualization for how predictions vary over time.\index{prediction error curve}
Prediction error curves are mostly used as a graphical guide when comparing few models, rather than as a formal tool for model comparison.
Example prediction error curves are provided in @fig-eval-pecs for the ISBS where the Cox PH consistently outperforms the SVM.

<!-- FIXME (ANDREAS): SAME PROBLEM AS CALIB CHAPTER - CAN'T RECREATE THESE ANYMORE USING PROBA BUT THEME IS WRONG; WHAT DO YOU THINK? -->
![Prediction error curves for the CPH and SVM models from @sec-eval-distr-calib. x-axis is time and y-axis is the ISBS computed at different time-points. The CPH (red) performs better than the SVM (blue) as it scores consistently lower. Trained and tested on randomly simulated data from $\pkg{mlr3proba}$.](Figures/evaluation/pecs.png){#fig-eval-pecs fig-alt="x-axis is Time from 0 to 5, y-axis is Score from 0 to 1. A red curve (Cox PH) runs from (0,0) to around (2.5, 0.25) and plateaus. A blue curve (SVM) runs from (0,0) to (1,0.8) down to around (4.5,0.3). The Cox PH appears superior at all time points."}

## Baselines and ERV {#sec-eval-distr-score-base}

A common criticism of scoring rules is a lack of interpretability, for example, an ISBS of 0.5 or 0.0005 has no meaning by itself, so below we present two methods to help overcome this problem.

The first method is to make use of baselines\index{model baselines} for model comparison, which are models or values that can be utilized to provide a reference for a loss and provide a universal method to judge all models of the same class [@Gressmann2018].
In classification, it is possible to derive analytical baseline values, for example a Brier score is considered 'bad' if it is above 0.25 or a log loss if it is above 0.693 (@fig-eval-brierlog).
This is because these are the values obtained if you always predicted probabilities as $0.5$, which is the best un-informed (i.e., data independent) baseline in a binary classification problem.
In survival analysis, simple analytical expressions are not possible as losses are dependent on the unknown distributions of both the survival and censoring time.
For this reason it is advisable to include baseline models for model comparison.
Common baselines include the Kaplan-Meier estimator (@sec-surv-km) and Cox PH (@sec-ph-semi-parametric). \index{Kaplan-Meier estimator}\index{Cox PH}
As a rule of thumb, if a model performs worse than the Kaplan-Meier, then it's considered 'bad', whereas if it outperforms the Cox PH then it is considered 'good'.

As well as directly comparing losses from a 'sophisticated' model to a baseline, one can also compute the percentage increase in performance between the sophisticated and baseline models, which produces a measure of explained residual variation (ERV) [@Korn1990; @Korn1991].
For any survival loss $L$, the ERV is,\index{explained residual variation}

$$
R_L(S, B) = 1 - \frac{L_{ \vertS}}{L_{ \vertB}}
$$

where $L_{ \vertS}$ and $L_{ \vertB}$ are the losses computed with respect to predictions from the sophisticated and baseline models respectively.

The ERV interpretation makes reporting of scoring rules easier within and between experiments.
For example, say in experiment A we have $L_{ \vertS} = 0.004$ and $L_{ \vertB} = 0.006$, and in experiment B we have $L_{ \vertS} = 4$ and $L_{ \vertB} = 6$.
The sophisticated model may appear worse at first glance in experiment A (as the losses are very close) but when considering the ERV we see that the performance increase is identical (both $R_L = 33\%$), thus providing a clearer way to compare models.

## Competing risks {#sec-rules-ext}

Similarly to discrimination measures, scoring rules are primarily used with competing risks by evaluating cause-specific probabilities individually [@vanGeloven2022; @Lee2018a; @Bender2021].\index{competing risks}

For example, let $\hatS_{i;q}$ be the predicted cause-specific survival for observation $i$ and cause $q$, then the right-censored log loss for event $\tilde{q} \in \{1,...,Q\}$ is defined as\index{right-censored log loss!cause-specific}

$$
L_{RCLL;\tilde{q}}(\hatS_{i;\tilde{q}}, t_i, q_i) = -\log[\II(q_i = \tilde{q})\hatf_{i;\tilde{q}}(t_i) + \II(q_i \ne \tilde{q})\hatS_{i;\tilde{q}}(t_i)],
$$

where $\hatf_{i;\tilde{q}}$ can be derived from $\hatS_{i;\tilde{q}}$ and $q_i$ is the observed cause for observation $i$.
Similar logic can be applied to the ISBS and other scoring rules.

<!-- TODO (ANDREAS): CHECK YOU'RE HAPPY WITH BELOW. STRICTLY G SHOULD HAVE COVARIATES AND A SUBSCRIPT i BUT I ADDED AN EXPLANATION IN THE CALLOUT BOX ABOVE. ALSO THE LOSS IS NEW AND I DON'T KNOW HOW WIDELY USED IT IS SO ARGUABLY DOESN'T NEED TO BE IN THE BOOK IN FULL? IT'S ALSO INTRODUCED IN THEIR PAPER FOR BOOSTING, DON'T KNOW IF THERE'S ANY INDEPENDENT STUDIES OUTSIDE OF THAT CONTEXT. ALSO NOTE THEY INTRODUCED AS A SCORE TO MAXIMIZE SO I ADDED THE MINUS BEFORE IT TO ENSURE IT'S A LOSS FIX/KEEP/REMOVE AS YOU LIKE. -->

Recently, an all-cause logarithmic scoring rule, termed here the all-cause log loss, has been proposed which also makes use of IPC weighting [@Alberge2025]:\index{all-cause log loss}

$$
\begin{aligned}
& L_{ACLL}(\tau^*, \hatS_i, \{\hatF_{i;q}\}^Q_{q=1}, t_i, q_i \mid \hatG) = \\
& \quad -\int^{\tau^*}_0 \left[\sum^Q_{q=1} \frac{\II(t_i \leq \tau, q_i = q)\log(\hatF_{i;q}(\tau))}{\hatG(t_i)} + \frac{\II(t_i > \tau)\log(\hatS_i(\tau))}{\hatG(\tau)}\right] \dtau,
\end{aligned}
$$

where $\hatS_i$ is the predicted all-cause survival function for observation $i$ and $\hatF_{i;q}$ is the predicted CIF for observation $i$ and cause $q$.\index{cumulative incidence function}
@Alberge2025 introduce the loss in the context of a boosting algorithm (@sec-boost), where the censoring survival function $\hatG$ is estimated iteratively alongside the event model; the representation above is presented in a more general form (Box 3).

This 'all-cause' loss is an adaptation of the ISLL (@sec-rules-log) \index{integrated survival log loss} with the weights modified to handle competing risks.
Comparing this loss to the decomposition in @sec-rules-squared, for each cause $q$, observations either: experience the cause of interest, in which case their cause-specific CIF is evaluated; do not experience any cause and so the all-cause survival is evaluated; or experience a different cause and contribute zero to the term for cause $q$.

One advantage of the all-cause loss is that it provides a single scalar quantity, which makes it particularly convenient for (automated) model comparison, especially when there are many competing causes.
However, this convenience comes at a cost as optimizing a single all-cause loss can obscure heterogeneity in performance across causes.
This is especially problematic when accurate modeling of some causes is more important than others.
Moreover, a model may achieve good overall performance while substantially underperforming for a clinically important cause.
As a result, when performance for individual causes is a priority, cause-specific scoring rules may be preferable.
In such settings, automated procedures, such as those used for hyperparameter optimization (@sec-ml), would require multi-objective optimization methods [@Morales-Hernandez2023].\index{tuning}

## Conclusion

:::: {.callout-warning icon=false}

## Key takeaways

* Scoring rules are a useful tool for measuring a model's overall predictive ability, taking into account calibration and discrimination.
* Strictly proper scoring rules allow models to be compared to one another, which is important when choosing models in a benchmark experiment.
* Many scoring rules for censored data are *not* strictly proper, however experiments suggest that improper rules still provide useful and trustworthy results [@Sonabend2025].
* Scoring rules can be difficult to interpret but ERV representations can be a helpful way to overcome this.
* There is no consensus about which scoring rule to use and when so in practice multiple scoring rules may have to be reported in experiments to ensure transparency and fairness of results.
* For non- and semi-parametric survival models that return distribution predictions, estimates of $f(t)$ are not readily available and require approximations [@Rindt2022], hence logarithmic losses such as RCLL often cannot be directly used in practice.

::::

:::: {.callout-tip icon=false}

## Further reading

* @Dawid2014 and @Gneiting2007 provide a comprehensive summary of scoring rules in regression and classification settings.
* @Rindt2022, @Sonabend2025 and @Yanagisawa2023 review survival scoring rules, including loss forms not discussed in this chapter such as pinball losses.
* @Choodari2012a, @Choodari2012b, and @Rahman2017 compare measures for external validation including some scoring rules.

::::
