on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build

jobs:
  build-book:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      # - name: Setup Julia
      #   uses: julia-actions/setup-julia@v1

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render book
        run: make render

      # - name: Publish to Netlify (and render)
      #   if: ${{ github.event_name == 'pull_request' }}
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: netlify
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     path: book/_book
      #     netlify_url: MLSA.netlify.app

      # - name: Publish to GitHub Pages (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages

      - name: Upload pdf book
        uses: actions/upload-artifact@v3
        with:
          name: MLSA
          path: book/_book/Machine-Learning-in-Survival-Analysis.pdf
          retention-days: 5
          
      - name: Add & Commit
        if: ${{ github.event_name == 'pull_request' }}
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: book/_book/Machine-Learning-in-Survival-Analysis.pdf --force
          message: 'Push pdf [skip ci]'

      - name: Comment link to pdf
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            [Book](https://github.com/RaphaelS1/MLSA/blob/${{ github.event.pull_request.head.ref }}/book/_book/Machine-Learning-in-Survival-Analysis.pdf)

      # - name: Deploy
      #   if: ${{ github.event_name == 'push' }}
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages
      #     folder: book/_book
      #     single-commit: true
