on:
  workflow_dispatch:
  push:
    branches:
      - main

name: build

jobs:
  build-book:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      # - name: Setup Julia
      #   uses: julia-actions/setup-julia@v1

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Restore renv
        run: |
          install.packages("renv")
          renv::restore("book/", prompt = FALSE, repos = getOption("repos"))

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: book/_book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
