on:
  workflow_dispatch:
  push:
    branches:
      - main

name: publish

jobs:
  build-book:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: book/_book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
